### PR TITLE
Remove nlohmann/json and tsl-ordered-map files, add rapidjson submodule

### PR DESCRIPTION
**Pull request by timwoj**
Related to https://github.com/zeek/zeek/issues/595

Note that the rapidjson repo used here is a clone of rapidjson under my user. I added a feature to the code to allow printing `null` for NaN and +/- infinity double values. I opened a PR on the main rapidjson repo, but it doesn't look like it's ever going to get merged.

If we want, I could see cloning the repo under the zeek project instead if the main repo decides not to merge that feature.

### CODE REVIEW

**Comment by jsiwek** [comment]
* Generally, if we need to make submodules for 3rdparty repos, I'd suggest having them point to forks just so that it's under our control and they can't do something wild and crazy to temporarily break us (e.g. unlikely but who knows if they decide to delete the repo or something)
* Are we essentially picking a "random" (i.e. recent) spot in the rapidjson `master` branch to point our submodule at?  Would be preferable to base it on a stable release, but they have nothing recent we can likely use and also not satisfying to say "wait for one" since it's been so long already (last was in 2016), so not sure what else to suggest.
* Don't think it's too bad to maintain your patch for NaN/Infinity, but slight preference would be either that gets in upstream or else we can do the equivalent in an unpatched version using a custom output wrapper like they suggested.

**Comment by timwoj** [comment]
> Generally, if we need to make submodules for 3rdparty repos, I'd suggest having them point to forks just so that it's under our control and they can't do something wild and crazy to temporarily break us (e.g. unlikely but who knows if they decide to delete the repo or something)

Agreed. Currently it's pointed at a fork under my user, but we probably should create it under the zeek user and cherry-pick the change over to that.

> Are we essentially picking a "random" (i.e. recent) spot in the rapidjson master branch to point our submodule at? Would be preferable to base it on a stable release, but they have nothing recent we can likely use and also not satisfying to say "wait for one" since it's been so long already (last was in 2016), so not sure what else to suggest.

Yep. Before I opened the PR I rebased it to the current upstream master. They haven't done a release in forever and there's been a lot of changes since then.

> Don't think it's too bad to maintain your patch for NaN/Infinity, but slight preference would be either that gets in upstream or else we can do the equivalent in an unpatched version using a custom output wrapper like they suggested.

I'll look into it.

**Comment by timwoj** [comment]
I reworked the zeek code to not need the change I made anymore, so I redid the submodule to point directly at the main repo.

**Comment by rsmmr** [comment]
I'm going to fork this to zeek/rapidjson and that have the submodule point there.

**Pull request merged**
